### ISSUE TITLE
potential bug

### ISSUE THREAD

**Issue by aldurgham1** [leftfield-geospatial/simple-ortho#3]
Hi, the simple-ortho code runs really nice, i love it.
I am facing one issue, the output image looks pixalized/bulky non-smooth. I tried all interpolation combinations and i tried to force constant resolution between input and output but was unable to fix.

Any idea how to fix that?

**Comment by dugalh** [comment]
Hello.  I haven't seen something like this before.  Both the `interp` and `dem_interp` parameters are relevant.  Can you share the code / command line and configuration that is giving you this problem?  Also, what are the resolutions (pixel sizes in meters) of your source, DEM and output images?

**Comment by aldurgham1** [comment]
Hi Harris, thank you so much for the reply.

1-attached, please see the problem i am trying to solve. Picture shows a
solution from simple-ortho and a ERDAS software side by side for the same
data.

2-The image resolution is 0.10 meter. The DEM resolution is 0.5 m. Attached
see sample configuration i use.

3- I tried to debug the code for the resampling and transformation stages,
but could not see anything strange.

4- Also, I tried all options for interpolation for DEM and Image,
different resolutions even (.01,.01)  but I will see this issue.

Thanks,

[image: image.png]

Sample config

[image: image.png]

**Comment by aldurgham1** [comment]
![IMG_2165](https://github.com/leftfield-geospatial/simple-ortho/assets/49416415/7a1d5343-ad21-48d1-86fb-ed761122a2e4)
![IMG_2166](https://github.com/leftfield-geospatial/simple-ortho/assets/49416415/d2c0d036-8d71-4d64-a90c-3256a3b66b5e)

**Comment by aldurgham1** [comment]
thanks for your replay. yes the resolution is 10cm. 

i noticed that the output ortho has different sampling for x and y, it was 50cm for Y while it was 10 cm for X.

I am debugging the function "_remap_src_to_ortho" to see what went wrong on my side. 

thanks again!


![image](https://github.com/leftfield-geospatial/simple-ortho/assets/49416415/bf984ccd-c670-40c4-ae37-46cbbb93c515)

**Comment by aldurgham1** [comment]
hi, the issue was data truncation due to using np.32 precision on a double precision coordinates. This was linked to using open cv remapping. Fixed by using double precision and switching to the scipy option for remapping.

hope this was useful. in case if someone ran to same problem

**Comment by dugalh** [comment]
Great - thanks for the debugging...

**Comment by dugalh** [comment]
Hi @aldurgham1.  I came across the same precision issue - it should be fixed in the current version.  Co-ordinate calculations are done in *float64* now, except for [the remapping](https://github.com/leftfield-geospatial/simple-ortho/blob/c91eab3670a04dee096a39bd860b84f7da12a26a/simple_ortho/ortho.py#L340) where the smaller range pixel co-ordinates are converted to *float32* for `cv2.remap()`.  Thanks for reporting.
