### ISSUE TITLE
please help me :((

### ISSUE THREAD

**Issue by xxsle** [leftfield-geospatial/simple-ortho#6]
hi. hope you are doing well. can i use your work to do ortho-rectification by running my own dem yield with my own overlay aerial images?

**Comment by dugalh** [comment]
Hello.  I'm not too sure what you mean.  If you know your [camera parameters](https://github.com/leftfield-geospatial/simple-ortho#configuration-file) (focal length, sensor size and image size) and have accurate [camera position/orientation](https://github.com/leftfield-geospatial/simple-ortho#camera-position-and-orientation) (camera position in projected/world co-ordinates with omega, phi, kappa angles), then it should work for you.

**Comment by xxsle** [comment]
first I wanted to use your data and run it but I think your input image files are missing. can you share the data files with me?

**Comment by dugalh** [comment]
The data should be included in the repository, in the data/inputs/text_example directory.
