### ISSUE TITLE
running

### ISSUE THREAD

**Issue by xxsle** [leftfield-geospatial/simple-ortho#8]
Hello. is there any error in the code that will prevent it from running? I can't run it. can you explain in detail how I should run the code? I would be very grateful if you can.

**Comment by dugalh** [comment]
Hello. Please send the command line or code snippet you are using, and the error message you get.

**Comment by xxsle** [comment]
the project runned with default arguments (rgb tif file, dem tif file, pos ori file) 

but rasterio raised some kind errors like; PHOTOMETRIC=YCBCR requires COMPRESS=JPEG

i dont know much what is that but i did convert the tif file to jpeg binary and i see the stored image. i have passed the new rgb tif file, firstly jpeg extension and then tif extension but a new exception raised from program. 

the new one is about crs configuration, i look the source code and i've passed a parameter in exif.py based in rio.open(fp, mode, crs=example_crs) but nothing changes. actually i have no idea how you can work it properly. the demo files are all of your files. 

please fix the issues and update the project.

![bb2e5115-ac53-4911-b861-5966c4e421f8](https://github.com/leftfield-geospatial/simple-ortho/assets/108673936/7a1ea7b2-3869-4a71-9b72-799c35350295)

**Comment by dugalh** [comment]
Hello, The [config.yaml](https://github.com/leftfield-geospatial/simple-ortho/blob/main/config.yaml) file is set up for the `simple-otho` example data.  You need to change the settings to get it to work with your camera & image data.  It sounds like your input tif image has a `photometric: ycbcr` setting, which is not compatible with `compress: deflate` in config.yaml.  To fix that you could try changing your `config.yaml` to have the `compress`, `interleave` and `photometric` options configured as:

```yaml
...
ortho:
  ...
  compress: deflate
  interleave: band
  photometric: minisblack
  ...
```

Then, you also need to set the `crs:` option in config.yaml to the CRS (projection) of your camera positions in camera_pos_ori.txt  if your input images have no CRS, are or not in the same CRS as your camera positions.  E.g.

```yaml
...
ortho: 
  crs: EPSG:<your EPSG code>
...
```

I am working on some changes that will simplify the configuration, and make some of this more obvious, but for now you need to use config.yaml.

**Comment by xxsle** [comment]
what exactly should i do here? i'm getting an error. pls help. "Note that if the source image is geo-referenced and has a co-ordinate reference system (CRS), the camera (Easting, Northing) position must be specified in the source CRS. Where the source image has no CRS, the CRS of the camera (Easting, Northing) position must be specified in [config.yaml](https://github.com/leftfield-geospatial/simple-ortho#configuration-file)."
![WhatsApp Image 2023-07-14 at 16 20 42](https://github.com/leftfield-geospatial/simple-ortho/assets/108673936/f12e3053-c5d1-4ac6-a57e-a4c0eb06f5d6)

**Comment by xxsle** [comment]
![WhatsApp Image 2023-07-14 at 16 41 03](https://github.com/leftfield-geospatial/simple-ortho/assets/108673936/6b39e2dc-df91-4ee4-922c-e7968c78e6be)
![WhatsApp Image 2023-07-14 at 16 41 04](https://github.com/leftfield-geospatial/simple-ortho/assets/108673936/569cdc3f-28c6-41d3-a7b5-0c642566c1bf)
rasterio._err.CPLE_AppDefinedError: Invalid coordinate
I fixed the crs part. it gives a new error. it says the coordinate is incorrect. what should I do? I would be very grateful if you can help.

**Comment by xxsle** [comment]
I'm getting errors even though I'm doing what you mentioned. how exactly did you get it to work? why am I getting so many errors?

**Comment by dugalh** [comment]
Based on the error message, it looks like there is no entry for 3324c_2015_1004_05_0182_RGB in camera_pos_ori.txt.

If you follow the guidelines in the readme, and have accurate camera parameter (position, orientation, focal length etc ) and DEM data, it should work.  I would start by running the [example](https://github.com/leftfield-geospatial/simple-ortho#example-application). 

If you have done all that and are getting an error, please share data and a command line to reproduce the error so that I can diagnose it.

**Comment by xxsle** [comment]
I wanted to run your data first anyway. could you please share all your input data with me? I can give you my e-mail address

**Comment by dugalh** [comment]
The data is in the repository.  Please follow the instructions in the readme.

**Comment by dugalh** [comment]
The command line in the image you posted above is not the same as in the readme example.  Please follow the [installation instructions](https://github.com/leftfield-geospatial/simple-ortho#installation) exactly.  Then change into the simple-ortho directory.

``` bash
cd simple-ortho
```
Then run the example.

``` bash
simple-ortho -v 2 -rc ./data/inputs/test_example/config.yaml -od ./data/outputs/test_example ./data/inputs/test_example/*RGB.tif ./data/inputs/test_example/dem.tif ./data/inputs/test_example/camera_pos_ori.txt
```

**Comment by xxsle** [comment]
![WhatsApp Image 2023-07-21 at 00 23 10](https://github.com/leftfield-geospatial/simple-ortho/assets/108673936/a67c6629-45e4-47e8-bf48-6bacd95465f5)
I get the result for a single image in this way. why do you think this happened? the overlay images did not overlap as you threw. where did I make a mistake. I would be very grateful if you could answer me. (the bottom one is your result)
![WhatsApp Image 2023-07-21 at 00 23 49](https://github.com/leftfield-geospatial/simple-ortho/assets/108673936/aee120d8-1962-4757-bf30-85241243b77f)

**Comment by dugalh** [comment]
`simple-ortho` produces a single orthorectified image for each source image.  To display a group of overlapping images in their geo-referenced locations, you could use something like [QGIS](https://www.qgis.org).
